<a href="https://colab.research.google.com/github/hargurjeet/MachineLearning/blob/master/30days_of_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Start

In [1]:
# Familiar imports
import numpy as np
import pandas as pd

# For ordinal encoding categorical variables, splitting data
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# For training random forest model
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from xgboost import XGBRegressor

!pip install opendatasets --quiet
import opendatasets as od
od.download('https://www.kaggle.com/c/30-days-of-ml/data')
od.download('https://www.kaggle.com/abhishek/30days-folds')

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: hargurjeet
Your Kaggle Key: ··········


100%|██████████| 66.0M/66.0M [00:01<00:00, 38.4MB/s]



Extracting archive ./30-days-of-ml/30-days-of-ml.zip to ./30-days-of-ml
Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: hargurjeet
Your Kaggle Key: ··········


100%|██████████| 40.1M/40.1M [00:01<00:00, 41.4MB/s]


In [2]:
# Load the training data
train = pd.read_csv("/content/30-days-of-ml/train.csv", index_col=0)
test = pd.read_csv("/content/30-days-of-ml/test.csv", index_col=0)
train_fold = pd.read_csv("/content/30days-folds/train_folds.csv", index_col=0)

# Separate target from features
y = train['target']
X = train.drop(['target'], axis=1)

low_cardinality_cols = [cname for cname in X.columns if X[cname].nunique() < 10 and X[cname].dtype == "object"]
numeric_cols = [cname for cname in X.columns if X[cname].dtype in ['int64', 'float64']]
object_cols = [cname for cname in X.columns if X[cname].dtype in ['object']]



X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state=42)

my_cols = low_cardinality_cols + numeric_cols
X_train = X_train[my_cols].copy()
X_valid = X_valid[my_cols].copy()
X_test = test[my_cols].copy()


OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(X_train[low_cardinality_cols]))
OH_cols_valid = pd.DataFrame(OH_encoder.transform(X_valid[low_cardinality_cols]))

scaler = StandardScaler()
# X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
# X_valid[numeric_cols] = scaler.transform(X_valid[numeric_cols])

scaler_cols_train = pd.DataFrame(scaler.fit_transform(X_train[numeric_cols]))
scaler_cols_valid = pd.DataFrame(scaler.transform(X_valid[numeric_cols]))

OH_cols_train.index = X_train.index
OH_cols_valid.index = X_valid.index
scaler_cols_train.index = X_train.index
scaler_cols_valid.index = X_valid.index

OH_X_train = pd.concat([scaler_cols_train, OH_cols_train], axis=1)
OH_X_valid = pd.concat([scaler_cols_valid, OH_cols_valid], axis=1)

# Base model

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

%time
model = RandomForestRegressor(n_estimators=500, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.91 µs
0.7307262530827241


# Trial 1

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

%time
model = RandomForestRegressor(n_estimators=250, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 9.3 µs
0.7315744282908309


In [ ]:
# with standardscaler
%%time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error


model = RandomForestRegressor(n_estimators=250, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.96 µs
0.7315779266693908


# Trail 2

In [ ]:
%%time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

%time
model = RandomForestRegressor(n_estimators=50, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.39 µs
0.7370585640514145
CPU times: user 6min 34s, sys: 2.26 s, total: 6min 36s
Wall time: 6min 33s


# Trail 3

In [ ]:
%%time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

%time
model = RandomForestRegressor(n_estimators=25, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.01 µs
0.745547885632514
CPU times: user 3min 11s, sys: 350 ms, total: 3min 11s
Wall time: 3min 10s


# Trail 4

In [ ]:
%%time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

%time
model = RandomForestRegressor(n_estimators=10, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.77 µs
0.76817552401976
CPU times: user 1min 16s, sys: 95.4 ms, total: 1min 16s
Wall time: 1min 15s


In [ ]:
#standard scaler
%%time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
model = RandomForestRegressor(n_estimators=10, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

0.7685131126247501
CPU times: user 1min 22s, sys: 1.95 s, total: 1min 24s
Wall time: 1min 24s


In [ ]:
OH_cols_test = pd.DataFrame(OH_encoder.transform(X_test[low_cardinality_cols]))
scaler_cols_test = pd.DataFrame(scaler.transform(X_test[numeric_cols]))
OH_cols_test.index = X_test.index
scaler_cols_test.index = X_test.index
OH_test = pd.concat([scaler_cols_test, OH_cols_test], axis=1)

# Use the model to generate predictions
predictions = model.predict(OH_test)

# Save the predictions to a CSV file
output = pd.DataFrame({'Id': X_test.index,
                       'target': predictions})
output.to_csv('submission.csv', index=False)

# Kfolds

In [ ]:
useful_features = [cname for cname in train_fold.columns if cname not in ['id','target','kfold' ]]

object_cols = [cname for cname in train_fold.columns if train_fold[cname].dtype in ['object']]

final_predictions = []
scores = []
for fold in range(5):
    xtrain =  train_fold[train_fold.kfold != fold].reset_index(drop=True)
    xvalid = train_fold[train_fold.kfold == fold].reset_index(drop=True)
    xtest = test.copy()

    ytrain = xtrain.target
    yvalid = xvalid.target
    
    xtrain = xtrain[useful_features]
    xvalid = xvalid[useful_features]
    
    ordinal_encoder = OrdinalEncoder()
    xtrain[object_cols] = ordinal_encoder.fit_transform(xtrain[object_cols])
    xvalid[object_cols] = ordinal_encoder.transform(xvalid[object_cols])
    xtest[object_cols] = ordinal_encoder.transform(xtest[object_cols])
    
    scaler = StandardScaler()
    xtrain[numeric_cols] = scaler.fit_transform(xtrain[numeric_cols])
    xvalid[numeric_cols] = scaler.transform(xvalid[numeric_cols])
    xtest[numeric_cols] = scaler.transform(xtest[numeric_cols])



    # model = RandomForestRegressor(n_estimators=10, random_state=42)
    model = XGBRegressor(random_state=fold)
    model.fit(xtrain, ytrain)
    preds_valid = model.predict(xvalid)
    test_preds = model.predict(xtest)
    final_predictions.append(test_preds)
    rmse = mean_squared_error(yvalid, preds_valid, squared=False)
    print(fold, rmse)
    scores.append(rmse)
    
print(np.mean(scores), np.std(scores))

[17:22:45] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
0 0.7303071547258375
[17:23:31] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
1 0.7300175230569053
[17:24:18] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
2 0.7318886172542051
[17:25:07] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
3 0.7315077897767691
[17:25:56] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
4 0.7312139590772474
0.7309870087781929 0.0007124213959477351


In [ ]:
final_predictions

[array([8.080743, 8.292851, 8.367263, ..., 8.326172, 8.102555, 8.168501],
       dtype=float32),
 array([8.048563, 8.30311 , 8.382118, ..., 8.337402, 8.094259, 8.192955],
       dtype=float32),
 array([8.092666, 8.287758, 8.346624, ..., 8.343813, 8.151852, 8.178483],
       dtype=float32),
 array([8.038809, 8.279227, 8.361634, ..., 8.31238 , 8.095289, 8.196581],
       dtype=float32),
 array([8.063913, 8.3034  , 8.386561, ..., 8.376184, 8.118031, 8.163134],
       dtype=float32)]

In [ ]:
predictions = np.mean(np.column_stack(final_predictions), axis=1)

In [ ]:
output = pd.DataFrame({'Id': test.index,
                       'target': predictions})
output.to_csv('submission.csv', index=False)

# Label encoding/ taget encoding

In [ ]:
useful_features = [cname for cname in train_fold.columns if cname not in ['id','target','kfold' ]]

object_cols = [cname for cname in train_fold.columns if train_fold[cname].dtype in ['object']]

final_predictions = []
scores = []

for col in object_cols:
    temp_df = []
    temp_test_feat = None
  for fold in range(5):
      xtrain =  train_fold[train_fold.kfold != fold].reset_index(drop=True)
      xvalid = train_fold[train_fold.kfold == fold].reset_index(drop=True)
      xtest = test.copy()

      feat = xtrain.groupby(col)["target"].agg("mean")
        feat = feat.to_dict()
        xvalid.loc[:, f"tar_enc_{col}"] = xvalid[col].map(feat)
        temp_df.append(xvalid)
        if temp_test_feat is None:
            temp_test_feat = df_test[col].map(feat)
        else:
            temp_test_feat += df_test[col].map(feat)
    
      temp_test_feat /= 5
      df_test.loc[:, f"tar_enc_{col}"] = temp_test_feat
      df = pd.concat(temp_df)

      ytrain = xtrain.target
      yvalid = xvalid.target
      
      xtrain = xtrain[useful_features]
      xvalid = xvalid[useful_features]
      
      ordinal_encoder = OrdinalEncoder()
      xtrain[object_cols] = ordinal_encoder.fit_transform(xtrain[object_cols])
      xvalid[object_cols] = ordinal_encoder.transform(xvalid[object_cols])
      xtest[object_cols] = ordinal_encoder.transform(xtest[object_cols])
      
      scaler = StandardScaler()
      xtrain[numeric_cols] = scaler.fit_transform(xtrain[numeric_cols])
      xvalid[numeric_cols] = scaler.transform(xvalid[numeric_cols])
      xtest[numeric_cols] = scaler.transform(xtest[numeric_cols])



      # model = RandomForestRegressor(n_estimators=10, random_state=42)
      model = XGBRegressor(random_state=fold)
      model.fit(xtrain, ytrain)
      preds_valid = model.predict(xvalid)
      test_preds = model.predict(xtest)
      final_predictions.append(test_preds)
      rmse = mean_squared_error(yvalid, preds_valid, squared=False)
      print(fold, rmse)
      scores.append(rmse)
      
print(np.mean(scores), np.std(scores))