<a href="https://colab.research.google.com/github/hargurjeet/MachineLearning/blob/master/rf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
# Familiar imports
import numpy as np
import pandas as pd

# For ordinal encoding categorical variables, splitting data
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# For training random forest model
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

!pip install opendatasets --quiet
import opendatasets as od
od.download('https://www.kaggle.com/c/30-days-of-ml/data')
od.download('https://www.kaggle.com/abhishek/30days-folds')

Skipping, found downloaded files in "./30-days-of-ml" (use force=True to force download)
Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: hargurjeet
Your Kaggle Key: ··········


100%|██████████| 40.1M/40.1M [00:00<00:00, 193MB/s]


In [20]:
# Load the training data
train = pd.read_csv("/content/30-days-of-ml/train.csv", index_col=0)
test = pd.read_csv("/content/30-days-of-ml/test.csv", index_col=0)
train_fold = pd.read_csv("/content/30days-folds/train_folds.csv", index_col=0)

# Separate target from features
y = train['target']
X = train.drop(['target'], axis=1)

low_cardinality_cols = [cname for cname in X.columns if X[cname].nunique() < 10 and X[cname].dtype == "object"]
numeric_cols = [cname for cname in X.columns if X[cname].dtype in ['int64', 'float64']]
object_cols = [cname for cname in X.columns if X[cname].dtype in ['object']]



X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state=42)

my_cols = low_cardinality_cols + numeric_cols
X_train = X_train[my_cols].copy()
X_valid = X_valid[my_cols].copy()
X_test = test[my_cols].copy()


OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(X_train[low_cardinality_cols]))
OH_cols_valid = pd.DataFrame(OH_encoder.transform(X_valid[low_cardinality_cols]))

scaler = StandardScaler()
# X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
# X_valid[numeric_cols] = scaler.transform(X_valid[numeric_cols])

scaler_cols_train = pd.DataFrame(scaler.fit_transform(X_train[numeric_cols]))
scaler_cols_valid = pd.DataFrame(scaler.transform(X_valid[numeric_cols]))

OH_cols_train.index = X_train.index
OH_cols_valid.index = X_valid.index
scaler_cols_train.index = X_train.index
scaler_cols_valid.index = X_valid.index

OH_X_train = pd.concat([scaler_cols_train, OH_cols_train], axis=1)
OH_X_valid = pd.concat([scaler_cols_valid, OH_cols_valid], axis=1)

# Base model

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

%time
model = RandomForestRegressor(n_estimators=500, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.91 µs
0.7307262530827241


# Trial 1

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

%time
model = RandomForestRegressor(n_estimators=250, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 9.3 µs
0.7315744282908309


In [11]:
# with standardscaler
%%time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error


model = RandomForestRegressor(n_estimators=250, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.96 µs
0.7315779266693908


# Trail 2

In [ ]:
%%time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

%time
model = RandomForestRegressor(n_estimators=50, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 7.39 µs
0.7370585640514145
CPU times: user 6min 34s, sys: 2.26 s, total: 6min 36s
Wall time: 6min 33s


# Trail 3

In [ ]:
%%time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

%time
model = RandomForestRegressor(n_estimators=25, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.01 µs
0.745547885632514
CPU times: user 3min 11s, sys: 350 ms, total: 3min 11s
Wall time: 3min 10s


# Trail 4

In [ ]:
%%time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

%time
model = RandomForestRegressor(n_estimators=10, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 4.77 µs
0.76817552401976
CPU times: user 1min 16s, sys: 95.4 ms, total: 1min 16s
Wall time: 1min 15s


In [12]:
#standard scaler
%%time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
model = RandomForestRegressor(n_estimators=10, random_state=42)
model.fit(OH_X_train, y_train)
preds = model.predict(OH_X_valid)

print(mean_squared_error(y_valid, preds, squared=False))

0.7685131126247501
CPU times: user 1min 22s, sys: 1.95 s, total: 1min 24s
Wall time: 1min 24s


In [13]:
OH_cols_test = pd.DataFrame(OH_encoder.transform(X_test[low_cardinality_cols]))
scaler_cols_test = pd.DataFrame(scaler.transform(X_test[numeric_cols]))
OH_cols_test.index = X_test.index
scaler_cols_test.index = X_test.index
OH_test = pd.concat([scaler_cols_test, OH_cols_test], axis=1)

# Use the model to generate predictions
predictions = model.predict(OH_test)

# Save the predictions to a CSV file
output = pd.DataFrame({'Id': X_test.index,
                       'target': predictions})
output.to_csv('submission.csv', index=False)

# Kfolds

In [24]:
useful_features = [cname for cname in train_fold.columns if cname not in ['id','target','kfold' ]]

object_cols = [cname for cname in train_fold.columns if train_fold[cname].dtype in ['object']]

final_predictions = []
scores = []
for fold in range(5):
    xtrain =  train_fold[train_fold.kfold != fold].reset_index(drop=True)
    xvalid = train_fold[train_fold.kfold == fold].reset_index(drop=True)
    xtest = test.copy()

    ytrain = xtrain.target
    yvalid = xvalid.target
    
    xtrain = xtrain[useful_features]
    xvalid = xvalid[useful_features]
    
    ordinal_encoder = OrdinalEncoder()
    xtrain[object_cols] = ordinal_encoder.fit_transform(xtrain[object_cols])
    xvalid[object_cols] = ordinal_encoder.transform(xvalid[object_cols])
    xtest[object_cols] = ordinal_encoder.transform(xtest[object_cols])
    
    scaler = StandardScaler()
    xtrain[numeric_cols] = scaler.fit_transform(xtrain[numeric_cols])
    xvalid[numeric_cols] = scaler.transform(xvalid[numeric_cols])
    xtest[numeric_cols] = scaler.transform(xtest[numeric_cols])



    model = RandomForestRegressor(n_estimators=10, random_state=42)
    model.fit(xtrain, ytrain)
    preds_valid = model.predict(xvalid)
    test_preds = model.predict(xtest)
    final_predictions.append(test_preds)
    rmse = mean_squared_error(yvalid, preds_valid, squared=False)
    print(fold, rmse)
    scores.append(rmse)
    
print(np.mean(scores), np.std(scores))

0 0.7702783129211256
1 0.7702433116106784
2 0.7716617411685681
3 0.7714196814892231
4 0.7720214196547849
0.771124893368876 0.000731129240033214


In [25]:
final_predictions

[array([8.10374108, 7.66498074, 7.85612563, ..., 8.21321667, 8.16022342,
        8.44475945]),
 array([8.08982173, 8.77936251, 8.45638352, ..., 8.37902358, 8.24278852,
        7.67338599]),
 array([8.05711585, 8.41855805, 8.23759357, ..., 8.2766095 , 8.03841509,
        8.32389592]),
 array([7.50010614, 8.33776135, 8.72716325, ..., 8.75153521, 7.9935197 ,
        7.86313445]),
 array([7.79202434, 8.62895359, 8.44571933, ..., 8.34944956, 8.26813406,
        8.10841684])]

In [29]:
predictions = np.mean(np.column_stack(final_predictions), axis=1)

In [30]:
output = pd.DataFrame({'Id': test.index,
                       'target': predictions})
output.to_csv('submission.csv', index=False)